### ISSUE TITLE
Update to be compatible with PocketMine latest build 

### ISSUE THREAD

**Issue by PermissionError** [XdmingXD/WhatTheServer#2]
As the title said, really needs this to be updated to log actions because we absolutely NEED it for grief detection and punishing players. Thanks!

**Comment by PatheticMing** [comment]
uhmm...it should be compatible

**Comment by PermissionError** [comment]
Nope, php 7.2? And the typehints update https://github.com/pmmp/PocketMine-MP/commit/697ea55fb746634ad743874b449f79b244adb618 and other new typehints
