### ISSUE TITLE
Server getting very laggy when using WTS

### ISSUE THREAD

**Issue by PermissionError** [XdmingXD/WhatTheServer#6]
I think there's an issue with the SQLite data provider. I'm not getting fast query speed on my server.

EDIT: PR #5

**Comment by PatheticMing** [comment]
More details please 
Does your server lag when you start the server or does it lag when you run the command?

**Comment by PermissionError** [comment]
As in #5 , lags when a little more players joined.

**Comment by PatheticMing** [comment]
alright...I would say you can switch it to normal if you want. However, I don't suggest switch it off : D
